package config

// Native root settings. Descendants and values require pinned schema or type validation.
var nativeSettingRegistry = map[string]map[string]map[string]bool{
	"codex": {
		"project": {"agents": true, "allow_login_shell": true, "analytics": true, "approval_policy": true, "approvals_reviewer": true, "apps": true, "auto_review": true, "background_terminal_max_timeout": true, "browser_use": true, "chatgpt_base_url": true, "check_for_update_on_startup": true, "cli_auth_credentials_store": true, "compact_prompt": true, "computer_use": true, "default_permissions": true, "desktop": true, "developer_instructions": true, "disable_paste_burst": true, "experimental_compact_prompt_file": true, "experimental_use_unified_exec_tool": true, "features": true, "feedback": true, "file_opener": true, "forced_chatgpt_workspace_id": true, "forced_login_method": true, "hide_agent_reasoning": true, "history": true, "hooks": true, "instructions": true, "log_dir": true, "marketplaces": true, "mcp_oauth_callback_port": true, "mcp_oauth_callback_url": true, "mcp_oauth_credentials_store": true, "mcp_optional_startup_grace_ms": true, "mcp_servers": true, "memories": true, "model": true, "model_auto_compact_token_limit": true, "model_auto_compact_token_limit_scope": true, "model_catalog_json": true, "model_context_window": true, "model_instructions_file": true, "model_provider": true, "model_providers": true, "model_reasoning_effort": true, "model_reasoning_summary": true, "model_supports_reasoning_summaries": true, "model_verbosity": true, "notice": true, "notify": true, "openai_base_url": true, "oss_provider": true, "permissions": true, "personality": true, "plan_mode_reasoning_effort": true, "plugins": true, "project_doc_fallback_filenames": true, "project_doc_max_bytes": true, "project_root_markers": true, "projects": true, "review_model": true, "sandbox_mode": true, "sandbox_workspace_write": true, "service_tier": true, "shell_environment_policy": true, "show_raw_agent_reasoning": true, "skills": true, "sqlite_home": true, "suppress_unstable_features_warning": true, "tool_output_token_limit": true, "tool_suggest": true, "tools": true, "tui": true, "web_search": true, "windows": true, "windows_wsl_setup_acknowledged": true},
		"user":    {"agents": true, "allow_login_shell": true, "analytics": true, "approval_policy": true, "approvals_reviewer": true, "apps": true, "auto_review": true, "background_terminal_max_timeout": true, "browser_use": true, "chatgpt_base_url": true, "check_for_update_on_startup": true, "cli_auth_credentials_store": true, "compact_prompt": true, "computer_use": true, "default_permissions": true, "desktop": true, "developer_instructions": true, "disable_paste_burst": true, "experimental_compact_prompt_file": true, "experimental_use_unified_exec_tool": true, "features": true, "feedback": true, "file_opener": true, "forced_chatgpt_workspace_id": true, "forced_login_method": true, "hide_agent_reasoning": true, "history": true, "hooks": true, "instructions": true, "log_dir": true, "marketplaces": true, "mcp_oauth_callback_port": true, "mcp_oauth_callback_url": true, "mcp_oauth_credentials_store": true, "mcp_optional_startup_grace_ms": true, "mcp_servers": true, "memories": true, "model": true, "model_auto_compact_token_limit": true, "model_auto_compact_token_limit_scope": true, "model_catalog_json": true, "model_context_window": true, "model_instructions_file": true, "model_provider": true, "model_providers": true, "model_reasoning_effort": true, "model_reasoning_summary": true, "model_supports_reasoning_summaries": true, "model_verbosity": true, "notice": true, "notify": true, "openai_base_url": true, "oss_provider": true, "otel": true, "permissions": true, "personality": true, "plan_mode_reasoning_effort": true, "plugins": true, "project_doc_fallback_filenames": true, "project_doc_max_bytes": true, "project_root_markers": true, "projects": true, "review_model": true, "sandbox_mode": true, "sandbox_workspace_write": true, "service_tier": true, "shell_environment_policy": true, "show_raw_agent_reasoning": true, "skills": true, "sqlite_home": true, "suppress_unstable_features_warning": true, "tool_output_token_limit": true, "tool_suggest": true, "tools": true, "tui": true, "web_search": true, "windows": true, "windows_wsl_setup_acknowledged": true},
	},
	"copilot": {
		"project": {"companyAnnouncements": true, "contextTier": true, "deniedUrls": true, "disableAllHooks": true, "disabledMcpServers": true, "disabledSkills": true, "effortLevel": true, "enabledPlugins": true, "extraKnownMarketplaces": true, "hooks": true, "includeCoAuthoredBy": true, "mergeStrategy": true, "model": true, "respectGitignore": true},
		"user":    {"allowedUrls": true, "askUser": true, "autoUpdate": true, "autoUpdatesChannel": true, "banner": true, "bannerStyle": true, "defaultMode": true, "inlineImages": true, "inlineImageLiveWindow": true, "notifications": true, "memory": true, "bashEnv": true, "beepOnSchedule": true, "beep": true, "builtInAgents": true, "colorMode": true, "commandHistoryMaxSize": true, "compactPaste": true, "companyAnnouncements": true, "continueOnAutoMode": true, "copyOnSelect": true, "customAgents": true, "deniedUrls": true, "disableAllHooks": true, "disabledMcpServers": true, "disabledSkills": true, "dynamicRetrieval": true, "effortLevel": true, "enabledMcpServers": true, "enabledPlugins": true, "experimental": true, "extraKnownMarketplaces": true, "footer": true, "hooks": true, "ide": true, "includeCoAuthoredBy": true, "keepAlive": true, "logLevel": true, "mergeStrategy": true, "model": true, "mouse": true, "permissions": true, "pinnedPrompts": true, "powershellFlags": true, "proxyKerberosServicePrincipal": true, "proxyUrl": true, "remoteExport": true, "remote": true, "renderHexColors": true, "renderMarkdown": true, "respectGitignore": true, "sandbox": true, "screenReader": true, "scrollbar": true, "shellShortcut": true, "showTimestamps": true, "showTipsOnStartup": true, "skillDirectories": true, "statusLine": true, "stayInAutopilot": true, "storeTokenPlaintext": true, "stream": true, "streamerMode": true, "subagents": true, "tabs": true, "terminalProgress": true, "theme": true, "toolSearch": true, "updateTerminalTitle": true, "worktreeBaseRef": true},
	},
}
