package config

// Native value types from the source-linked 2026-09-10 reference corpus.
var nativeSettingTypes = map[string]map[string]string{
	"codex": {
		"agents":                                                            "table",
		"agents.<name>.config_file":                                         "string (path)",
		"agents.<name>.description":                                         "string",
		"agents.default_subagent_model":                                     "string",
		"agents.default_subagent_reasoning_effort":                          "string",
		"agents.enabled":                                                    "boolean",
		"agents.interrupt_message":                                          "boolean",
		"agents.max_concurrent_threads_per_session":                         "number",
		"agents.max_threads":                                                "number",
		"allow_login_shell":                                                 "boolean",
		"analytics.enabled":                                                 "boolean",
		"approval_policy":                                                   "on-request | never | { granular = { sandbox_approval = bool, rules = bool, mcp_elicitations = bool, request_permissions = bool, skill_approval = bool } }",
		"approval_policy.granular.mcp_elicitations":                         "boolean",
		"approval_policy.granular.request_permissions":                      "boolean",
		"approval_policy.granular.rules":                                    "boolean",
		"approval_policy.granular.sandbox_approval":                         "boolean",
		"approval_policy.granular.skill_approval":                           "boolean",
		"approvals_reviewer":                                                "user | auto_review",
		"apps.<id>.approvals_reviewer":                                      "user | auto_review",
		"apps.<id>.default_tools_approval_mode":                             "auto | prompt | writes | approve",
		"apps.<id>.default_tools_enabled":                                   "boolean",
		"apps.<id>.destructive_enabled":                                     "boolean",
		"apps.<id>.enabled":                                                 "boolean",
		"apps.<id>.open_world_enabled":                                      "boolean",
		"apps.<id>.tools.<tool>.approval_mode":                              "auto | prompt | writes | approve",
		"apps.<id>.tools.<tool>.enabled":                                    "boolean",
		"apps._default.approvals_reviewer":                                  "user | auto_review",
		"apps._default.default_tools_approval_mode":                         "auto | prompt | writes | approve",
		"apps._default.destructive_enabled":                                 "boolean",
		"apps._default.enabled":                                             "boolean",
		"apps._default.open_world_enabled":                                  "boolean",
		"auto_review.policy":                                                "string",
		"background_terminal_max_timeout":                                   "number",
		"browser_use.allow_history_access":                                  "boolean",
		"browser_use.default_origin_policy":                                 "table",
		"browser_use.origins.<origin>":                                      "table",
		"chatgpt_base_url":                                                  "string",
		"check_for_update_on_startup":                                       "boolean",
		"cli_auth_credentials_store":                                        "file | keyring | auto | ephemeral",
		"compact_prompt":                                                    "string",
		"computer_use.default_app_access":                                   "allow | deny",
		"computer_use.macos.bundle_ids":                                     "map<string, allow | deny>",
		"computer_use.windows.always_allowed_app_ids":                       "array<string>",
		"computer_use.windows.aumids":                                       "map<string, allow | deny>",
		"computer_use.windows.exes":                                         "array<table>",
		"default_permissions":                                               "string",
		"desktop.custom_file_handlers.<id>":                                 "table",
		"desktop.custom_file_handlers.<id>.args":                            "array<string>",
		"desktop.custom_file_handlers.<id>.command":                         "string",
		"desktop.custom_file_handlers.<id>.icon":                            "string",
		"desktop.custom_file_handlers.<id>.input":                           "path | json_argument | json_stdin",
		"desktop.custom_file_handlers.<id>.label":                           "string",
		"desktop.custom_file_handlers.<id>.supports_ssh":                    "boolean",
		"developer_instructions":                                            "string",
		"disable_paste_burst":                                               "boolean",
		"experimental_compact_prompt_file":                                  "string (path)",
		"experimental_use_unified_exec_tool":                                "boolean",
		"features.apps":                                                     "boolean",
		"features.code_mode.direct_only_tool_namespaces":                    "array<string>",
		"features.code_mode.enabled":                                        "boolean",
		"features.code_mode.excluded_tool_namespaces":                       "array<string>",
		"features.context_management.experimental_mode":                     "boolean",
		"features.enable_request_compression":                               "boolean",
		"features.fast_mode":                                                "boolean",
		"features.goals":                                                    "boolean",
		"features.hooks":                                                    "boolean",
		"features.memories":                                                 "boolean",
		"features.multi_agent":                                              "boolean",
		"features.network_proxy":                                            "boolean | table",
		"features.network_proxy.allow_local_binding":                        "boolean",
		"features.network_proxy.allow_upstream_proxy":                       "boolean",
		"features.network_proxy.dangerously_allow_all_unix_sockets":         "boolean",
		"features.network_proxy.dangerously_allow_non_loopback_proxy":       "boolean",
		"features.network_proxy.domains":                                    "map<string, allow | deny>",
		"features.network_proxy.enable_socks5":                              "boolean",
		"features.network_proxy.enable_socks5_udp":                          "boolean",
		"features.network_proxy.enabled":                                    "boolean",
		"features.network_proxy.proxy_url":                                  "string",
		"features.network_proxy.socks_url":                                  "string",
		"features.network_proxy.unix_sockets":                               "map<string, allow | deny>",
		"features.personality":                                              "boolean",
		"features.prevent_idle_sleep":                                       "boolean",
		"features.remote_plugin":                                            "boolean",
		"features.rollout_budget.enabled":                                   "boolean",
		"features.rollout_budget.limit_tokens":                              "integer",
		"features.rollout_budget.prefill_token_weight":                      "number",
		"features.rollout_budget.reminder_interval_tokens":                  "integer",
		"features.rollout_budget.sampling_token_weight":                     "number",
		"features.shell_snapshot":                                           "boolean",
		"features.shell_tool":                                               "boolean",
		"features.skill_mcp_dependency_install":                             "boolean",
		"features.unified_exec":                                             "boolean",
		"features.web_search":                                               "boolean",
		"features.web_search_cached":                                        "boolean",
		"features.web_search_request":                                       "boolean",
		"feedback.enabled":                                                  "boolean",
		"file_opener":                                                       "vscode | vscode-insiders | windsurf | cursor | none",
		"forced_chatgpt_workspace_id":                                       "string (uuid)",
		"forced_login_method":                                               "chatgpt | api",
		"hide_agent_reasoning":                                              "boolean",
		"history.max_bytes":                                                 "number",
		"history.persistence":                                               "save-all | none",
		"hooks":                                                             "table",
		"hooks.<Event>":                                                     "array<table>",
		"hooks.<Event>[].hooks":                                             "array<table>",
		"hooks.<Event>[].hooks[].additionalContextLimit":                    "integer",
		"hooks.<Event>[].hooks[].async":                                     "boolean",
		"hooks.<Event>[].hooks[].commandWindows":                            "string",
		"instructions":                                                      "string",
		"log_dir":                                                           "string (path)",
		"marketplaces.<name>.ref":                                           "string",
		"marketplaces.<name>.source":                                        "string",
		"marketplaces.<name>.source_type":                                   "git | local",
		"marketplaces.<name>.sparse_paths":                                  "array<string>",
		"mcp_oauth_callback_port":                                           "integer",
		"mcp_oauth_callback_url":                                            "string",
		"mcp_oauth_credentials_store":                                       "auto | file | keyring",
		"mcp_optional_startup_grace_ms":                                     "integer (milliseconds)",
		"mcp_servers.<id>.args":                                             "array<string>",
		"mcp_servers.<id>.auth":                                             "oauth | chatgpt",
		"mcp_servers.<id>.bearer_token_env_var":                             "string",
		"mcp_servers.<id>.command":                                          "string",
		"mcp_servers.<id>.cwd":                                              "string",
		"mcp_servers.<id>.default_tools_approval_mode":                      "auto | prompt | writes | approve",
		"mcp_servers.<id>.disabled_tools":                                   "array<string>",
		"mcp_servers.<id>.enabled":                                          "boolean",
		"mcp_servers.<id>.enabled_tools":                                    "array<string>",
		"mcp_servers.<id>.env":                                              "map<string,string>",
		"mcp_servers.<id>.env_http_headers":                                 "map<string,string>",
		"mcp_servers.<id>.experimental_environment":                         "local | remote",
		"mcp_servers.<id>.http_headers":                                     "map<string,string>",
		"mcp_servers.<id>.http_headers_helper":                              "string (command)",
		"mcp_servers.<id>.oauth.callback_port":                              "integer",
		"mcp_servers.<id>.oauth.callback_url":                               "string",
		"mcp_servers.<id>.oauth.client_id":                                  "string",
		"mcp_servers.<id>.oauth_resource":                                   "string",
		"mcp_servers.<id>.required":                                         "boolean",
		"mcp_servers.<id>.scopes":                                           "array<string>",
		"mcp_servers.<id>.startup_timeout_ms":                               "number",
		"mcp_servers.<id>.startup_timeout_sec":                              "number",
		"mcp_servers.<id>.tool_timeout_sec":                                 "number",
		"mcp_servers.<id>.tools.<tool>.approval_mode":                       "auto | prompt | writes | approve",
		"mcp_servers.<id>.tools.<tool>.output_token_limit":                  "integer (positive)",
		"mcp_servers.<id>.url":                                              "string",
		"memories.consolidation_model":                                      "string",
		"memories.disable_on_external_context":                              "boolean",
		"memories.extract_model":                                            "string",
		"memories.generate_memories":                                        "boolean",
		"memories.max_raw_memories_for_consolidation":                       "number",
		"memories.max_rollout_age_days":                                     "number",
		"memories.max_rollouts_per_startup":                                 "number",
		"memories.max_unused_days":                                          "number",
		"memories.min_rate_limit_remaining_percent":                         "number",
		"memories.min_rollout_idle_hours":                                   "number",
		"memories.use_memories":                                             "boolean",
		"model":                                                             "string",
		"model_auto_compact_token_limit":                                    "number",
		"model_auto_compact_token_limit_scope":                              "total | body_after_prefix",
		"model_catalog_json":                                                "string (path)",
		"model_context_window":                                              "number",
		"model_instructions_file":                                           "string (path)",
		"model_provider":                                                    "string",
		"model_providers.<id>":                                              "table",
		"model_providers.<id>.auth":                                         "table",
		"model_providers.<id>.auth.args":                                    "array<string>",
		"model_providers.<id>.auth.command":                                 "string",
		"model_providers.<id>.auth.cwd":                                     "string (path)",
		"model_providers.<id>.auth.refresh_interval_ms":                     "number",
		"model_providers.<id>.auth.timeout_ms":                              "number",
		"model_providers.<id>.base_url":                                     "string",
		"model_providers.<id>.env_http_headers":                             "map<string,string>",
		"model_providers.<id>.env_key":                                      "string",
		"model_providers.<id>.env_key_instructions":                         "string",
		"model_providers.<id>.experimental_bearer_token":                    "string",
		"model_providers.<id>.http_headers":                                 "map<string,string>",
		"model_providers.<id>.name":                                         "string",
		"model_providers.<id>.query_params":                                 "map<string,string>",
		"model_providers.<id>.request_max_retries":                          "number",
		"model_providers.<id>.requires_openai_auth":                         "boolean",
		"model_providers.<id>.stream_idle_timeout_ms":                       "number",
		"model_providers.<id>.stream_max_retries":                           "number",
		"model_providers.<id>.supports_standalone_web_search":               "boolean",
		"model_providers.<id>.supports_websockets":                          "boolean",
		"model_providers.<id>.wire_api":                                     "responses",
		"model_providers.amazon-bedrock.aws.profile":                        "string",
		"model_providers.amazon-bedrock.aws.region":                         "string",
		"model_reasoning_effort":                                            "minimal | low | medium | high | xhigh",
		"model_reasoning_summary":                                           "auto | concise | detailed | none",
		"model_supports_reasoning_summaries":                                "boolean",
		"model_verbosity":                                                   "low | medium | high",
		"notice.hide_full_access_warning":                                   "boolean",
		"notice.hide_gpt-5.1-codex-max_migration_prompt":                    "boolean",
		"notice.hide_gpt5_1_migration_prompt":                               "boolean",
		"notice.hide_rate_limit_model_nudge":                                "boolean",
		"notice.hide_world_writable_warning":                                "boolean",
		"notice.model_migrations":                                           "map<string,string>",
		"notify":                                                            "array<string>",
		"openai_base_url":                                                   "string",
		"oss_provider":                                                      "lmstudio | ollama",
		"otel.environment":                                                  "string",
		"otel.exporter":                                                     "none | otlp-http | otlp-grpc",
		"otel.exporter.<id>.endpoint":                                       "string",
		"otel.exporter.<id>.headers":                                        "map<string,string>",
		"otel.exporter.<id>.protocol":                                       "binary | json",
		"otel.exporter.<id>.tls.ca-certificate":                             "string",
		"otel.exporter.<id>.tls.client-certificate":                         "string",
		"otel.exporter.<id>.tls.client-private-key":                         "string",
		"otel.log_user_prompt":                                              "boolean",
		"otel.metrics_exporter":                                             "none | statsig | otlp-http | otlp-grpc",
		"otel.trace_exporter":                                               "none | otlp-http | otlp-grpc",
		"otel.trace_exporter.<id>.endpoint":                                 "string",
		"otel.trace_exporter.<id>.headers":                                  "map<string,string>",
		"otel.trace_exporter.<id>.protocol":                                 "binary | json",
		"otel.trace_exporter.<id>.tls.ca-certificate":                       "string",
		"otel.trace_exporter.<id>.tls.client-certificate":                   "string",
		"otel.trace_exporter.<id>.tls.client-private-key":                   "string",
		"permissions.<name>.description":                                    "string",
		"permissions.<name>.extends":                                        "string",
		"permissions.<name>.filesystem":                                     "table",
		"permissions.<name>.filesystem.glob_scan_max_depth":                 "number",
		"permissions.<name>.network.allow_local_binding":                    "boolean",
		"permissions.<name>.network.allow_upstream_proxy":                   "boolean",
		"permissions.<name>.network.dangerously_allow_all_unix_sockets":     "boolean",
		"permissions.<name>.network.dangerously_allow_non_loopback_proxy":   "boolean",
		"permissions.<name>.network.domains":                                "table",
		"permissions.<name>.network.domains.<pattern>":                      "allow | deny",
		"permissions.<name>.network.enable_socks5":                          "boolean",
		"permissions.<name>.network.enable_socks5_udp":                      "boolean",
		"permissions.<name>.network.enabled":                                "boolean",
		"permissions.<name>.network.mode":                                   "limited | full",
		"permissions.<name>.network.proxy_url":                              "string",
		"permissions.<name>.network.socks_url":                              "string",
		"permissions.<name>.network.unix_sockets":                           "table",
		"permissions.<name>.network.unix_sockets.<path>":                    "allow | deny",
		"permissions.<name>.workspace_roots":                                "table",
		"permissions.<name>.workspace_roots.<path>":                         "boolean",
		"personality":                                                       "none | friendly | pragmatic",
		"plan_mode_reasoning_effort":                                        "none | minimal | low | medium | high | xhigh",
		"plugins.<plugin>.enabled":                                          "boolean",
		"plugins.<plugin>.mcp_servers.<server>.default_tools_approval_mode": "auto | prompt | writes | approve",
		"plugins.<plugin>.mcp_servers.<server>.disabled_tools":              "array<string>",
		"plugins.<plugin>.mcp_servers.<server>.enabled":                     "boolean",
		"plugins.<plugin>.mcp_servers.<server>.enabled_tools":               "array<string>",
		"plugins.<plugin>.mcp_servers.<server>.tools.<tool>.approval_mode":  "auto | prompt | writes | approve",
		"project_doc_fallback_filenames":                                    "array<string>",
		"project_doc_max_bytes":                                             "number",
		"project_root_markers":                                              "array<string>",
		"projects.<path>.trust_level":                                       "string",
		"review_model":                                                      "string",
		"sandbox_mode":                                                      "read-only | workspace-write | danger-full-access",
		"sandbox_workspace_write.exclude_slash_tmp":                         "boolean",
		"sandbox_workspace_write.exclude_tmpdir_env_var":                    "boolean",
		"sandbox_workspace_write.network_access":                            "boolean",
		"sandbox_workspace_write.writable_roots":                            "array<string>",
		"service_tier":                                                      "string",
		"shell_environment_policy.exclude":                                  "array<string>",
		"shell_environment_policy.experimental_use_profile":                 "boolean",
		"shell_environment_policy.filters":                                  "map<string, include | exclude>",
		"shell_environment_policy.ignore_default_excludes":                  "boolean",
		"shell_environment_policy.include_only":                             "array<string>",
		"shell_environment_policy.inherit":                                  "all | core | none",
		"shell_environment_policy.set":                                      "map<string,string>",
		"show_raw_agent_reasoning":                                          "boolean",
		"skills.config":                                                     "array<object>",
		"skills.config.<index>.enabled":                                     "boolean",
		"skills.config.<index>.path":                                        "string (path)",
		"skills.max_context_tokens":                                         "integer (positive)",
		"sqlite_home":                                                       "string (path)",
		"suppress_unstable_features_warning":                                "boolean",
		"tool_output_token_limit":                                           "number",
		"tool_suggest.disabled_tools":                                       "array<table>",
		"tool_suggest.discoverables":                                        "array<table>",
		"tools.view_image":                                                  "boolean",
		"tui":                                                               "table",
		"tui.alternate_screen":                                              "auto | always | never",
		"tui.animations":                                                    "boolean",
		"tui.keymap.<context>.<action>":                                     "string | array<string>",
		"tui.keymap.<context>.<action> = []":                                "empty array",
		"tui.model_availability_nux.<model>":                                "integer",
		"tui.notification_condition":                                        "unfocused | always",
		"tui.notification_method":                                           "auto | osc9 | bel",
		"tui.notifications":                                                 "boolean | array<string>",
		"tui.raw_output_mode":                                               "boolean",
		"tui.resume_cwd":                                                    "current | session",
		"tui.show_tooltips":                                                 "boolean",
		"tui.status_line":                                                   "array<string> | null",
		"tui.terminal_title":                                                "array<string> | null",
		"tui.theme":                                                         "string",
		"tui.vim_mode_default":                                              "boolean",
		"web_search":                                                        "disabled | cached | indexed | live",
		"windows.sandbox":                                                   "unelevated | elevated",
		"windows.sandbox_private_desktop":                                   "boolean",
		"windows_wsl_setup_acknowledged":                                    "boolean",
	},
	"copilot": {
		"#":                                  "Comment line.",
		"*":                                  "Allow all models (default when no file is present).",
		"Bash(...)`, `Shell(...)":            "Shell commands. Use <command> * (for example, git push *) to match a command prefix; otherwise the rule matches exact text.",
		"Domain(...)":                        "URL hostnames, matched like [URL rules](/en/copilot/reference/copilot-cli-reference/cli-command-reference#tool-permission-patterns).",
		"Edit(...)`, `Write(...)":            "File write/edit paths, matched the same way as Read(...).",
		"GLOB-PATTERN":                       "Allow model IDs matching the glob (for example, claude-sonnet-*).",
		"MODEL-ID":                           "Allow an exact model ID.",
		"PowerShell(...)":                    "PowerShell commands, matched the same way as Shell(...).",
		"Read(...)":                          "File read/view paths. Supports glob patterns: / for the workspace root, ~/ for the home directory, and ./ for the current working directory.",
		"agents/":                            "Directory",
		"agents/`, `skills/`, `hooks/":       "Not recommended",
		"allowedMcpServers":                  "Allowlist of MCP servers users may load, matched by serverUrl, serverCommand, or serverName. Trusted first-party servers (for example, the built-in GitHub MCP server) are always exempt. Leaving this key unset allows all non-default servers; an empty array denies all of them. See [Managed MCP server allow/deny list](#managed-mcp-server-allowdeny-list).",
		"allowedUrls":                        "string[]",
		"askUser":                            "boolean",
		"autoUpdate":                         "boolean",
		"autoUpdatesChannel":                 "\"stable\" | \"prerelease\"",
		"banner":                             "\"always\" | \"once\" | \"never\"",
		"defaultMode":                        `"interactive" | "plan" | "autopilot"`,
		"defaultPermissionMode":              `"manual" | "assisted" | "allow-all"`,
		"inlineImages":                       "boolean",
		"inlineImageLiveWindow":              "integer",
		"notifications":                      "boolean",
		"statusLine.type":                    `"command"`,
		"statusLine.command":                 "string",
		"statusLine.padding":                 "integer",
		"statusLine.refreshInterval":         "integer",
		"bannerStyle":                        "\"mona\" | \"classic\"",
		"bashEnv":                            "boolean",
		"beep":                               "boolean",
		"beepOnSchedule":                     "boolean",
		"builtInAgents.rubberDuck":           "boolean",
		"builtInAgents.rubberDuckAutoInvoke": "boolean",
		"colorMode":                          "\"default\" | \"github\" | \"dim\" | \"high-contrast\" | \"colorblind\"",
		"command-history-state/":             "Directory",
		"commandHistoryMaxSize":              "number",
		"commandIdentifiers":                 "Array of strings",
		"commands":                           "commandIdentifiers",
		"compactPaste":                       "boolean",
		"companyAnnouncements":               "string[]",
		"config.json":                        "File",
		"contextTier":                        "\"default\" | \"long_context\"",
		"continueOnAutoMode":                 "boolean",
		"copilot-instructions.md":            "File",
		"copilot-instructions.md`, `instructions/": "Not recommended",
		"copyOnSelect":                          "boolean",
		"custom-tool":                           "toolName",
		"customAgents.defaultLocalOnly":         "boolean",
		"deniedMcpServers":                      "Denylist of MCP servers that must never load, matched the same way as allowedMcpServers. A matching non-default server is blocked regardless of the allowlist\u2014deny always wins. See [Managed MCP server allow/deny list](#managed-mcp-server-allowdeny-list).",
		"deniedUrls":                            "string[]",
		"disableAllHooks":                       "boolean",
		"disabledMcpServers":                    "string[]",
		"disabledSkills":                        "string[]",
		"dynamicRetrieval":                      "{ skills?: boolean }",
		"effortLevel":                           "string",
		"enabledMcpServers":                     "string[]",
		"enabledPlugins":                        "Record<string, boolean>",
		"experimental":                          "boolean",
		"extension-management":                  "None",
		"extension-permission-access":           "extensionName",
		"extensionName":                         "String",
		"extensions/":                           "Directory",
		"extraKnownMarketplaces":                "Record<string, {...}>",
		"fallback: MODEL-ID":                    "Required exactly once. The model Copilot uses when the active model isn't allowed.",
		"footer":                                "object",
		"forceRemoteSettingsRefresh":            "Require a fresh server-managed settings fetch on startup, even when a fresh cached policy exists. The cached entry is still kept as a fallback if the fetch fails. The device (MDM) value takes precedence over a cached server value.",
		"gh pr:*":                               "gh pr, gh pr view, gh pr create",
		"git status":                            "git status",
		"git:*":                                 "git, git status, git push",
		"hooks":                                 "object",
		"hooks/":                                "Directory",
		"ide.autoConnect":                       "boolean",
		"ide.openDiffOnEdit":                    "boolean",
		"ide/":                                  "Directory",
		"includeCoAuthoredBy":                   "boolean",
		"installed-plugins/":                    "Directory",
		"instructions/":                         "Directory",
		"keepAlive":                             "\"on\" | \"off\" | \"busy\"",
		"kind":                                  "Required fields",
		"locations":                             "Object",
		"locations.<key>":                       "Object",
		"locations.<key>.allowed_directories":   "Array of strings",
		"locations.<key>.tool_approvals":        "Array",
		"locations.<key>.tool_approvals[].kind": "String",
		"logLevel":                              "\"none\" | \"error\" | \"warning\" | \"info\" | \"debug\" | \"all\" | \"default\"",
		"logs/":                                 "Directory",
		"lsp-config.json":                       "File",
		"mcp":                                   "serverName, toolName",
		"mcp-config.json":                       "File",
		"mcp-oauth-config/":                     "Directory",
		"mcp-sampling":                          "serverName",
		"mcp-secrets/":                          "Directory",
		"memory":                                "boolean",
		"mergeStrategy":                         "\"rebase\" | \"merge\"",
		"model":                                 "string",
		"mouse":                                 "boolean",
		"operation":                             "String",
		"permissions":                           "Set managed permissions, including disableBypassPermissionsMode and deny / ask / allow rule arrays. See [Managed permission rules](#managed-permission-rules).",
		"permissions-config.json":               "File",
		"permissions.disableBypassPermissionsMode": "string",
		"pinnedPrompts":                  "boolean",
		"plugin-data/":                   "Directory",
		"policyHelper":                   "Register an executable that supplies the lowest-priority managed-settings layer. Fields: path (required), plus optional args, timeoutMs, and refreshIntervalMs. If both a device (MDM) and a server policy register a policyHelper, the device registration wins.",
		"powershellFlags":                "string[]",
		"proxyKerberosServicePrincipal":  "string",
		"proxyUrl":                       "string",
		"read":                           "None",
		"remote":                         "\"on\" | \"off\"",
		"remoteControl":                  "Control whether sessions on this device can be controlled from other devices. mode is \"enabled\", \"disabled\", or \"requireSSO\" (requires githubDotComOrganizations when set).",
		"remoteExport":                   "boolean",
		"renderHexColors":                "boolean",
		"renderMarkdown":                 "boolean",
		"respectGitignore":               "boolean",
		"sandbox":                        "Set a sandbox policy floor that users cannot relax. Supported settings include enabled, failIfUnavailable, allowBypass, addCurrentWorkingDirectory, sandboxMcpServers, sandboxLspServers, auth.git, auth.gh, allowDevToolAccess, and the userPolicy.* filesystem and network rules. The managed value always takes precedence over a user's own value in the safer direction. Turning the sandbox on, requiring it to succeed, and sandboxing MCP and LSP servers cannot be turned off. Disabling bypass or credential injection cannot be re-enabled. Filesystem allow lists can only be narrowed, and denied paths can only be added to. failIfUnavailable can only be set by an administrator and blocks the session when the sandbox cannot be established. For the settings users can set themselves, see [User settings](#user-settings-copilotsettingsjson) or run copilot help sandbox.",
		"sandbox.allowBypass":            "boolean",
		"sandbox.auth.gh":                "boolean",
		"sandbox.auth.git":               "boolean",
		"sandbox.enabled":                "boolean",
		"sandbox.userPolicy.deniedPaths": "string[]",
		"sandbox.userPolicy.network.allowLocalNetwork": "boolean",
		"sandbox.userPolicy.network.proxy":             "object",
		"sandbox.userPolicy.seatbelt.keychainAccess":   "boolean",
		"screenReader":                        "boolean",
		"scrollbar":                           "boolean",
		"serverCommand":                       "A stdio server by its exact command and arguments, in order",
		"serverName":                          "String",
		"serverUrl":                           "A remote (HTTP/SSE) server by URL",
		"session-state/":                      "Directory",
		"session-store.db":                    "File",
		"settings.json":                       "File",
		"shellShortcut":                       "boolean",
		"showTimestamps":                      "boolean",
		"showTipsOnStartup":                   "boolean",
		"skillDirectories":                    "string[]",
		"skills/":                             "Directory",
		"statusLine":                          "object",
		"stayInAutopilot":                     "boolean",
		"storeTokenPlaintext":                 "boolean",
		"stream":                              "boolean",
		"streamerMode":                        "boolean",
		"strictKnownMarketplaces":             "Restrict plugins to known marketplaces",
		"subagents.agents":                    "object",
		"subagents.agents.<name>":             "object",
		"subagents.agents.<name>.model":       "string",
		"subagents.agents.<name>.effortLevel": `"low" | "medium" | "high" | "xhigh" | "inherit"`,
		"subagents.agents.<name>.contextTier": `"default" | "long_context" | "inherit"`,
		"subagents.disabledSubagents":         "string[]",
		"subagents.maxConcurrency":            "integer (positive)",
		"subagents.maxDepth":                  "integer (positive)",
		"tabs.enabled":                        "boolean",
		"tabs.hide":                           "string[]",
		"tabs.sort":                           "string[]",
		"telemetry":                           "Push baseline OpenTelemetry export configuration: enabled, endpoint, protocol, headers, resourceAttributes, captureContent, lockCaptureContent, and serviceName. See [GitHub Copilot CLI command reference](/en/copilot/reference/copilot-cli-reference/cli-command-reference#opentelemetry-monitoring).",
		"terminalProgress":                    "boolean",
		"theme":                               "\"default\" | \"github\" | \"dim\" | \"high-contrast\" | \"colorblind\"",
		"toolName":                            "String or null",
		"toolSearch":                          "boolean",
		"updateTerminalTitle":                 "boolean",
		"worktreeBaseRef":                     "\"head\" | \"defaultBranch\"",
		"write":                               "None",
	},
}
